Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init-local' at Sat, 01 Sep 2018 20:02:29 +0000. Up 8.99 seconds.
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Sep 01 20:02:29 cloud-init[1895]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 01 20:02:29 cloud-init[1895]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Sep 01 20:02:29 cloud-init[1895]: __init__.py[DEBUG]: Searching for data source in: []
Sep 01 20:02:29 cloud-init[1895]: cloud-init[DEBUG]: No local datasource found
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Sep 01 20:02:29 cloud-init[1895]: util.py[DEBUG]: cloud-init mode 'init' took 0.111 seconds (0.11)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init' at Sat, 01 Sep 2018 20:02:30 +0000. Up 9.39 seconds.
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: cloud-init[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/data/no-net (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: cloud-init[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Searching for data source in: ['DataSourceEc2', 'DataSourceNone']
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/ec2/meta-data (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 50.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/user-data' with {'url': 'http://169.254.169.254/latest/user-data', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/user-data (200, 2929b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/' with {'url': 'http://169.254.169.254/latest/meta-data/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ (200, 255b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/root', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/' with {'url': 'http://169.254.169.254/latest/meta-data/iam/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/ (200, 26b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/info' with {'url': 'http://169.254.169.254/latest/meta-data/iam/info', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/info (200, 216b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/ (200, 7b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/vhostmd', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/' with {'url': 'http://169.254.169.254/latest/meta-data/network/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/ (200, 11b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ (200, 230b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ipv4-associations/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ipv4-associations/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ipv4-associations/ (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ipv4-associations/34.210.60.252' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ipv4-associations/34.210.60.252', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/ipv4-associations/34.210.60.252 (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/local-hostname (200, 43b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/security-groups (200, 56b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/public-hostname (200, 49b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-ipv4-cidr-blocks', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/subnet-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/subnet-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/subnet-id (200, 15b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/public-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/public-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/public-ipv4s (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/interface-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/interface-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/interface-id (200, 21b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/mac' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/mac (200, 17b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/security-group-ids' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/security-group-ids', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/security-group-ids (200, 20b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/local-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/local-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/local-ipv4s (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/owner-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/owner-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/owner-id (200, 12b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/subnet-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/device-number' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/device-number', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/device-number (200, 1b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:4b:4e:2b:50:56/vpc-id (200, 12b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/' with {'url': 'http://169.254.169.254/latest/meta-data/placement/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/ (200, 17b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/latest/meta-data/placement/availability-zone', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/availability-zone (200, 10b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/' with {'url': 'http://169.254.169.254/latest/meta-data/services/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/ (200, 16b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/domain' with {'url': 'http://169.254.169.254/latest/meta-data/services/domain', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/domain (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/partition' with {'url': 'http://169.254.169.254/latest/meta-data/services/partition', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/partition (200, 3b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/profile' with {'url': 'http://169.254.169.254/latest/meta-data/profile', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/profile (200, 11b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/local-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-ipv4 (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/reservation-id' with {'url': 'http://169.254.169.254/latest/meta-data/reservation-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/reservation-id (200, 19b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-hostname (200, 43b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/security-groups (200, 56b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/latest/meta-data/ami-launch-index', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-launch-index (200, 1b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-hostname (200, 49b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/hostname' with {'url': 'http://169.254.169.254/latest/meta-data/hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/hostname (200, 43b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-id' with {'url': 'http://169.254.169.254/latest/meta-data/ami-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-id (200, 21b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-action' with {'url': 'http://169.254.169.254/latest/meta-data/instance-action', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-action (200, 4b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/mac' with {'url': 'http://169.254.169.254/latest/meta-data/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/mac (200, 17b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/public-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-ipv4 (200, 13b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/latest/meta-data/ami-manifest-path', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-type' with {'url': 'http://169.254.169.254/latest/meta-data/instance-type', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-type (200, 8b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity (200, 33b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/document', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/document (200, 477b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/signature', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 (200, 1118b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 01 20:02:30 cloud-init[1903]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
Sep 01 20:02:30 cloud-init[1903]: DataSourceEc2.py[DEBUG]: Crawl of metadata service took 0 seconds
Sep 01 20:02:30 cloud-init[1903]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 111 bytes from /proc/cmdline
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-09b8fd177925f2007'
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-09b8fd177925f2007/datasource (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/datasource - wb: [644] 29 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: cloud-init[DEBUG]: init will now be targeting instance id: i-09b8fd177925f2007
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 111 bytes from /proc/cmdline
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 11338 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/user-data.txt - wb: [600] 2929 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 105 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/user-data.txt.i - wb: [600] 2988 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/vendor-data.txt - wb: [600] 4 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/vendor-data.txt.i - wb: [600] 345 bytes
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/consume_data - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/consume_data'>)
Sep 01 20:02:30 cloud-init[1903]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: {'Content-Transfer-Encoding': '7bit', 'Content-Type': 'text/cloud-config; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="cloud-config.txt"', 'MIME-Version': '1.0'}
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 105 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: {'Content-Transfer-Encoding': '7bit', 'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="user-data.txt"', 'MIME-Version': '1.0'}
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 2279 bytes
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/cloud-config.txt - wb: [600] 155 bytes
Sep 01 20:02:30 cloud-init[1903]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: no vendordata from datasource
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 111 bytes from /proc/cmdline
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 155 bytes from /var/lib/cloud/instance/cloud-config.txt
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 155 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 155 bytes from /var/lib/cloud/instance/cloud-config.txt
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Attempting to load yaml from string of length 155 with allowed root types (<type 'dict'>,)
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 01 20:02:30 cloud-init[1903]: stages.py[INFO]: Skipping modules ['resolv-conf'] because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f21c0db8490>)
Sep 01 20:02:30 cloud-init[1903]: cc_migrator.py[DEBUG]: Migrating semaphores which are not named canonically.
Sep 01 20:02:30 cloud-init[1903]: cc_migrator.py[DEBUG]: Looking at consume_data
Sep 01 20:02:30 cloud-init[1903]: cc_migrator.py[DEBUG]: Searching for legacy per-instance semaphores under /var/lib/cloud/sem
Sep 01 20:02:30 cloud-init[1903]: cc_migrator.py[DEBUG]: Migrating semaphores which have been renamed or split.
Sep 01 20:02:30 cloud-init[1903]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/instances/i-09b8fd177925f2007/sem
Sep 01 20:02:30 cloud-init[1903]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/sem
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_rsyslog - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_rsyslog'>)
Sep 01 20:02:30 cloud-init[1903]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f21c169dcd0>)
Sep 01 20:02:30 cloud-init[1903]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_write_files - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_write_files'>)
Sep 01 20:02:30 cloud-init[1903]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_write_metadata - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_write_metadata'>)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f21cf309750>)
Sep 01 20:02:30 cloud-init[1903]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/1903/mountinfo (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 527 bytes from /proc/1903/mountinfo
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: resize_devices took 0.065 seconds
Sep 01 20:02:30 cloud-init[1903]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f21c12feb90>)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/1903/mountinfo (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 527 bytes from /proc/1903/mountinfo
Sep 01 20:02:30 cloud-init[1903]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 53 bytes from /proc/1/environ
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Read 1297 bytes from /proc/self/status
Sep 01 20:02:30 cloud-init[1903]: cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Forked child 1946 who will run callback log_time
Sep 01 20:02:30 cloud-init[1903]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=ext4, val=noblock)
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_set_hostname - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_set_hostname'>)
Sep 01 20:02:30 cloud-init[1903]: cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set-hostname
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f21c0b2c350>)
Sep 01 20:02:30 cloud-init[1903]: cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update-hostname
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f21c0b2c290>)
Sep 01 20:02:30 cloud-init[1946]: util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:30 cloud-init[1903]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_resolv_conf - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_resolv_conf'>)
Sep 01 20:02:30 cloud-init[1903]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Sep 01 20:02:30 cloud-init[1903]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_users_groups - wb: [644] 20 bytes
Sep 01 20:02:30 cloud-init[1903]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_users_groups'>)
Sep 01 20:02:30 cloud-init[1946]: util.py[DEBUG]: backgrounded Resizing took 0.011 seconds
Sep 01 20:02:30 cloud-init[1903]: __init__.py[INFO]: User ec2-user already exists, skipping.
Sep 01 20:02:30 cloud-init[1903]: util.py[DEBUG]: Running command ['usermod', '-L', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Read 3729 bytes from /etc/sudoers
Sep 01 20:02:31 cloud-init[1903]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_ssh - wb: [644] 20 bytes
Sep 01 20:02:31 cloud-init[1903]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_ssh'>)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 500:500
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 500:500
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Read 565 bytes from /root/.ssh/authorized_keys
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 565 bytes
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Sep 01 20:02:31 cloud-init[1903]: cloud-init[DEBUG]: Ran 13 modules with 0 failures
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Sep 01 20:02:31 cloud-init[1903]: util.py[DEBUG]: cloud-init mode 'init' took 1.309 seconds (1.30)
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:config' at Sat, 01 Sep 2018 20:02:31 +0000. Up 10.99 seconds.
Sep 01 20:02:31 cloud-init[1965]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 01 20:02:31 cloud-init[1965]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_mounts - wb: [644] 20 bytes
Sep 01 20:02:31 cloud-init[1965]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_mounts'>)
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Sep 01 20:02:31 cloud-init[1965]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Sep 01 20:02:31 cloud-init[1965]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: changed swap => None
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Sep 01 20:02:31 cloud-init[1965]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount ephemeral0
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Sep 01 20:02:31 cloud-init[1965]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount swap
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: no need to setup swap
Sep 01 20:02:31 cloud-init[1965]: cc_mounts.py[DEBUG]: No modifications to fstab needed.
Sep 01 20:02:31 cloud-init[1965]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_locale - wb: [644] 20 bytes
Sep 01 20:02:31 cloud-init[1965]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_locale'>)
Sep 01 20:02:31 cloud-init[1965]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Reading from /etc/sysconfig/i18n (quiet=False)
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Read 17 bytes from /etc/sysconfig/i18n
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Writing to /etc/sysconfig/i18n - wb: [644] 17 bytes
Sep 01 20:02:31 cloud-init[1965]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_set_passwords - wb: [644] 20 bytes
Sep 01 20:02:31 cloud-init[1965]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_set_passwords'>)
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Sep 01 20:02:31 cloud-init[1965]: cc_set_passwords.py[DEBUG]: Replacing auth line 65 with no
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [644] 3935 bytes
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Running command ['service', 'sshd', 'status'] with allowed return codes [0] (shell=False, capture=True)
Sep 01 20:02:31 cloud-init[1965]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Sep 01 20:02:31 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_yum_configure - wb: [644] 20 bytes
Sep 01 20:02:31 cloud-init[1965]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_yum_configure'>)
Sep 01 20:02:31 cloud-init[1965]: cc_yum_configure.py[DEBUG]: Generating default repo files
Sep 01 20:02:32 cloud-init[1965]: __init__.py[DEBUG]: filtered distro mirror info: {'regional': u'repo.us-west-2.amazonaws.com'}
Sep 01 20:02:32 cloud-init[1965]: cc_yum_configure.py[DEBUG]: Using mirror: repo.us-west-2.amazonaws.com
Sep 01 20:02:32 cloud-init[1965]: cc_yum_configure.py[INFO]: Setting yum releasever to 2018.03
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Writing to /etc/yum.conf - wb: [644] 1065 bytes
Sep 01 20:02:32 cloud-init[1965]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_yum_add_repo - wb: [644] 20 bytes
Sep 01 20:02:32 cloud-init[1965]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_yum_add_repo'>)
Sep 01 20:02:32 cloud-init[1965]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Sep 01 20:02:32 cloud-init[1965]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Sep 01 20:02:32 cloud-init[1965]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_package_update_upgrade_install'>)
Sep 01 20:02:32 cloud-init[1965]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_timezone - wb: [644] 20 bytes
Sep 01 20:02:32 cloud-init[1965]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_timezone'>)
Sep 01 20:02:32 cloud-init[1965]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Sep 01 20:02:32 cloud-init[1965]: stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_puppet.pyc'>) with frequency once-per-instance
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_puppet - wb: [644] 20 bytes
Sep 01 20:02:32 cloud-init[1965]: helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_puppet'>)
Sep 01 20:02:32 cloud-init[1965]: cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
Sep 01 20:02:32 cloud-init[1965]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Sep 01 20:02:32 cloud-init[1965]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f41238f8410>)
Sep 01 20:02:32 cloud-init[1965]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Sep 01 20:02:32 cloud-init[1965]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_runcmd - wb: [644] 20 bytes
Sep 01 20:02:32 cloud-init[1965]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-09b8fd177925f2007/sem/config_runcmd'>)
Sep 01 20:02:32 cloud-init[1965]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Sep 01 20:02:32 cloud-init[1965]: cloud-init[DEBUG]: Ran 10 modules with 0 failures
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Sep 01 20:02:32 cloud-init[1965]: util.py[DEBUG]: cloud-init mode 'modules' took 0.403 seconds (0.40)
Sep 01 20:02:32 cloud-init[2077]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:final' at Sat, 01 Sep 2018 20:02:32 +0000. Up 12.08 seconds.
Sep 01 20:02:32 cloud-init[2077]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 01 20:02:32 cloud-init[2077]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency always
Sep 01 20:02:32 cloud-init[2077]: helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f371ade7450>)
Sep 01 20:02:32 cloud-init[2077]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=True, capture=False)
Sep 01 20:02:52 cloud-init[2077]: cloud-init[DEBUG]: Ran 1 modules with 0 failures
Sep 01 20:02:52 cloud-init[2077]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Sep 01 20:02:52 cloud-init[2077]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 01 20:02:52 cloud-init[2077]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Sep 01 20:02:52 cloud-init[2077]: util.py[DEBUG]: cloud-init mode 'modules' took 20.026 seconds (18.20)
